{% set name = "syntheseus" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}-pkg
  version: {{ version }}

source:
  url: https://github.com/microsoft/syntheseus/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5aa7d882195e5467598e6d4f5c252bb8bb768725e7f216df17525ec909c97131

build:
  number: 1

outputs:
  - name: {{ name }}
    script: build-pkg.sh
    build:
      noarch: python
      entry_points:
        - {{ name }} = {{ name }}.cli.main:main

    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - networkx
        - numpy
        - more_itertools
        - omegaconf
        - python >=3.7
        - rdkit
        - tqdm

    test:
      commands:
        - command -v syntheseus
      imports:
        - syntheseus
        - syntheseus.interface
        - syntheseus.search

  - name: {{ name }}-viz
    build:
      noarch: generic
    requirements:
      run:
        - {{ name }} =={{ version }}
        - pillow
        - python-graphviz

    test:
      commands:
        - command -v syntheseus
      imports:
        - syntheseus
        - syntheseus.interface
        - syntheseus.search

about:
  home: https://github.com/microsoft/syntheseus
  summary: Benchmarking Chemical Synthesis Planning Algorithms
  description: |
    Syntheseus is a package for retrosynthetic planning. It contains implementations
    of common search algorithms and a simple API to wrap custom reaction models and
    write custom algorithms. It is meant to allow for simple benchmarking of
    the components of retrosynthesis algorithms.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
